site_url: royletron.github.io/toby
baby:
  fullname: Toby Albert Lanyon-Royle
  displayname: Toby
  sex: m
events:
  - name: Birth
    title: Toby's Birthday.
    menu: true
    icon: maki-pitch
    place: The John Radcliffe Hospital Oxford
    description: Welcome to the world Toby, time to make a mess!
    date: 2014-02-07
    time: 20:32
    photos: 
      - src: IMG_0012.jpg
  - name: First Poop!
    title: Toby does a poop.
    icon: fontawesome-umbrella
    place: The John Radcliffe Hospital Oxford
    description: Not only a poop, but also managing to wee over daddy!
    date: 2014-02-08
    time: 6:20
    photos: 
      - src: IMG_0007.jpg
  - name: Ten Poop!
    title: Tenth poop.
    icon: fontawesome-umbrella
    place: The John Radcliffe Hospital Oxford
    description: Not only a poop, but also managing to wee over daddy!
    date: 2014-02-08
    time: 6:20
    photos: 
      - src: IMG_0007.jpg