site_url: royletron.github.io/toby
baby:
  fullname: Toby Albert Lanyon-Royle
  displayname: Toby
  sex: m
events:
  - name: Birth
    title: Toby's Birthday.
    menu: true
    icon: maki-pitch
    place: The John Radcliffe Hospital Oxford
    description: Welcome to the world Toby, time to make a mess!
    date: 2014-02-07
    time: 20:32
    photos: 
      - src: IMG_0012.jpg
  - name: The Northerners
    title: Toby Meets Some Northerners
    icon: maki-toilet
    place: The John Radcliffe Hospital Oxford
    description: Toby meets his northern grandparents. NanAnn and GrandPhil
    date: 2014-02-15
    time: 15:30
    photos:
      - src: P1070724.JPG
  - name: Go Home
    title: Toby Goes Home.
    icon: fontawesome-home
    place: Home in Abingdon
    description: After a short stay in hospital, Toby goes home.
    date: 2014-02-15
    time: 21:30
    photos:
      - src: P1070709.JPG
  - name: First Park Visit
    title: Toby Goes To The Park
    icon: maki-tree-2
    place: Albert Park, Abingdon
    description: Toby takes his first visit of many to the park that was named after him.
    date: 2014-02-16
    time: 17:34
    photos:
      - src: P1070728.JPG
      - src: P1070730.JPG
      - src: P1070734.JPG
      - src: P1070735.JPG
      - src: P1070736.JPG